# .github/workflows/release.yml

on: [push]

name: Binary release

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux targets
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: arm-unknown-linux-musleabi
            os: ubuntu-latest
          - target: i686-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          # windows targets
          - target: i686-pc-windows-msvc
            os: windows-latest
            ext: .exe
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: .exe
          # darwin targets
          - target: aarch64-apple-darwin
            os: macOS-latest
          - target: x86_64-apple-darwin
            os: macOS-latest
    name: release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: db1000n-updater-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/db1000n-updater${{ matrix.ext }}
