# .github/workflows/release.yml

on: [push]

name: Binary release

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            aarch64-unknown-linux-musl,
            aarch64-apple-darwin,
            arm-unknown-linux-musleabi,
            armv7-unknown-linux-musleabi,
            i686-pc-windows-msvc,
            i686-unknown-linux-musl,
            x86_64-apple-darwin,
            x86_64-pc-windows-msvc,
            x86_64-unknown-linux-musl,
            x86_64-unknown-linux-gnu,
          ]
        cross: [true, false]
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{matrix.cross}}
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: db1000n-updater-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/db1000n-updater
